# Training Configuration for GPT-OSS-20B Fine-tuning
model:
  name: "mistral-7b"
  base_model: "mistralai/Mistral-7B-v0.1"  # Kein Gate, fits in 32GB VRAM
  trust_remote_code: false
  
data:
  # CSV Daten-Konfiguration
  data_dir: "data"
  train_csv: "training_data_lang_70pct.csv"
  validation_csv: "training_data_lang_15pct_1.csv"
  test_csv: "training_data_lang_15pct_2.csv"
  text_column: "chunk_text"
  label_column: "frame_name"  # Single label column (Spaltenname in CSV)
  max_length: 128  # Drastically reduced for memory efficiency
  # Label mapping
  label2id:
    "Conflict": 0
    "Moral Value": 1
    "Economic": 2
    "Powerlessness": 3
    "None": 4
    "Human Impact": 5
  num_labels: 6
  
training:
  # LoRA Configuration für effizientes Training
  use_lora: true
  lora_r: 4  # Further reduced for memory efficiency
  lora_alpha: 8  # Further reduced
  lora_dropout: 0.05
  lora_target_modules: ["q_proj", "v_proj"]  # Minimal target modules
  
  # Training Hyperparameters
  num_epochs: 3
  batch_size: 1  # Reduced for memory efficiency
  gradient_accumulation_steps: 4  # Effektive Batch Size: 4
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_steps: 100
  max_grad_norm: 1.0
  
  # Mixed Precision Training
  fp16: false
  bf16: true  # RTX 5090 (Blackwell) unterstützt BF16 nativ
  
  # Optimizer
  optimizer: "adamw_torch"
  lr_scheduler: "cosine"
  
  # Logging
  logging_steps: 10
  eval_steps: 200  # Less frequent evaluation for speed
  save_steps: 400  # Must be multiple of eval_steps
  save_total_limit: 2  # Keep fewer checkpoints
  
  # Output
  output_dir: "./outputs"
  checkpoint_dir: "./checkpoints"
  
hardware:
  gpu: "H100"  # RunPod H100
  num_gpus: 1
  device_map: "auto"
  
evaluation:
  metric: "f1_macro"  # Für Multi-Label-Klassifikation
  batch_size: 1  # Match training batch size
